### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by mollykc** [mollykc/mos-herb-site#3]
1. Replace text with: 

Healthcare should be personal, thorough, and integrated. -- make this a header or bigger in some way

Want to work to shift the root patterns that are causing your symptoms, without increasing your medications?

I can help you advocate for yourself in a conventional setting as well as give you the tools to understand your body from an herbal perspective -- one that integrates modern scientific research with centuries of tradition of botanical uses.

I have experience supporting clients with: -- bullet points
diabetes
Hashimoto’s thyroiditis and fatigue
sleep issues
depression and anxiety
migraines
GI dysregulation - diverticulitis, constipation, etc.
gender-affirming hormone therapy
immune support
allergies and asthma
skin issues, inc. MRSA infections and wound healing
and much, much more!

2. Make bullet points indented right

**Comment by maxtkc** [comment]
fixed
